/* Generated by camel build tools - do NOT edit this file! */
package demo.camel;

/**
 * Override URI factory provided by Camel to make it work with our new scheme saagie-kubernetes-custom-resources
 */
public class KubernetesCustomResourcesEndpointUriFactory extends org.apache.camel.component.kubernetes.customresources.KubernetesCustomResourcesEndpointUriFactory {
    @Override
    public boolean isEnabled(String scheme) {
        return "saagie-kubernetes-custom-resources".equals(scheme);
    }
}

